services:
    lime_calendar.voter.owner:
        class: Lime\CalendarBundle\Security\Authorization\Voter\OwnerVoter
        public: false
        arguments:
            classes: [%lime_calendar.model.calendar.class%, %lime_calendar.model.event.class%]
    lime_calendar.voter.participant:
        class: Lime\CalendarBundle\Security\Authorization\Voter\ParticipantVoter
        public: false
        arguments:
            em: "@doctrine.orm.entity_manager"
            class: %lime_calendar.model.event.class%
    lime_calendar.voter.member:
        class: Lime\CalendarBundle\Security\Authorization\Voter\MemberVoter
        public: false
        arguments:
            em: "@doctrine.orm.entity_manager"
            class: %lime_calendar.model.calendar.class%

    lime_calendar.voter:
        class: Symfony\Component\Security\Core\Authorization\AccessDecisionManager
        arguments:
            voters: ["@lime_calendar.voter.owner", "@lime_calendar.voter.participant", "@lime_calendar.voter.member"]
